### ISSUE TITLE
is gtk-doc really needed to compile atril from git checkout?

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/atril#565] opened 2022-05-30 15:39 UTC
I am trying to compile atril from latest git.

./autogen.sh
/usr/bin/mate-autogen
/usr/bin/yelp-build
checking for autoreconf >= 2.53...
  testing autoreconf... found 2.69
checking for pkg-config >= 0.14.0...
  testing pkg-config... found 0.29.2
checking for gtk-doc >= 1.13...
  testing gtkdocize... not found.
***Error***: You must have gtk-doc >= 1.13 installed
  to build atril.  Download the appropriate package for
  from your distribution or get the source tarball at
    http://ftp.gnome.org/pub/GNOME/sources/gtk-doc/

I don't need gtk-doc. Is it really needed? I'll compile it,
then try to compile atril, but I wonder because I don't
really need any local documentation.

**Comment by lukefromdc** [comment] 2022-05-31 04:49
Try building with
 --enable-gtk-doc=no
this is supposed to be the default but maybe the build system is checking for it
anyway. If this does not allow your build to finish without gtk-doc, this is a bug
in the build system, namely checking for a package that is not being actually
used. If your build does work, it's a bug in the defaults doing the same thing

**Comment by raveit65** [comment] 2022-08-06 15:34
Closing , not a bug.

**Closed by raveit65** 2022-08-06 15:34 UTC
