### ISSUE TITLE
Thumbnails in sidebar disappear after fast scrolling

### ISSUE THREAD

**Issue by Photon89** [mate-desktop/atril#255] opened 2017-06-19 12:40 UTC
#### Expected behaviour

Thumbnails should be always visible

#### Actual behaviour

Thumbnails sometimes disappear after fast scrolling

#### Steps to reproduce the behaviour

Open a PDF with many pages (I tested with a PDF of 140 pages). Scroll down within the sidebar. The thumbnails might take a  bit to get shown but they will get shown eventually. However, if you scroll fast, the thumbnails will disappear. They also won't appear if you stop scrolling and wait. To make them visible you have to scroll slowly till you reach some thumbnails which are actually shown. You can then slowly scroll back to see the previously invisible thumbnails. But they will disappear again if you scroll quickly. 

edit: Just noticed: You can make the hidden thumbnails visible by touching (hovering) the separation line between the sidebar and the main PDF with the cursor as well.

#### MATE general version

None, I use Atril in Xfce

#### Package version

1.18.0

#### Linux Distribution

Arch Linux

Similar bug in evince: https://bugzilla.gnome.org/show_bug.cgi?id=701537

**Comment by oliveiraleo** [comment] 2017-06-22 14:06
@Photon89 I have the same issue. I'm on Arch Linux too, but using MATE 1.18.0 and Atril (1.18.0) has same thing.
My tip is to not maximize the PDF window, it works for me in thumbnail disappearing.

**Comment by TomaszGasior** [comment] 2017-07-23 12:54
I can confirm this bug on Atril. Evince is not affected. Please see my movie with comparison Evince vs Atril.
[vokoscreen-2017-07-23_14-35-52.mp4.zip](https://github.com/mate-desktop/atril/files/1168070/vokoscreen-2017-07-23_14-35-52.mp4.zip)

Manjaro Linux
atril 1.18.0-1
evince 3.24.0+12+g717df38f-1

**Comment by Photon89** [comment] 2017-07-23 13:02
It's interesting that three people are hit by this issue and all of us use Arch/Manjaro. Maybe a packaging problem in the end? Here is Atril's Arch package: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/atril

**Comment by raveit65** [comment] 2017-08-13 13:49
Same in fedora 26.

**Comment by TomaszGasior** [comment] 2017-08-13 15:25
I found that this bug exists in original Evince in version 3.24.0 but it is fixed in 3.24.1. Can someone find a commit that fixes this bug and apply to Atril?

**Comment by Photon89** [comment] 2017-08-13 15:33
Maybe this: https://bugzilla.gnome.org/attachment.cgi?id=352756&action=diff ? This seems to fix https://bugzilla.gnome.org/show_bug.cgi?id=691448 which sounds similar to what we observe in Atril.

**Comment by TomaszGasior** [comment] 2017-08-13 15:35
Maybe this?
https://github.com/GNOME/evince/commit/8b24be3b5606e9279d1fb50b908efd1e1ef12a7b

**Comment by Photon89** [comment] 2017-08-13 15:40
Yep, we posted exactly the same thing. :)

**Comment by raveit65** [comment] 2017-08-13 15:42
I have found them already, i am just creating a pull request for testing.
Main fix is https://git.gnome.org/browse/evince/commit/?id=6480c7039bdf7e8f15f7d1415460db255910c40b

**Comment by Photon89** [comment] 2017-08-13 15:43
Maybe some of us should test it first and report if it actually helps?

**Comment by raveit65** [comment] 2017-08-13 16:37
Please test, see commit header for detailed description.

**Closed** 2017-08-15 12:11 UTC
Labels: confirmed

**Comment by raveit65** [comment] 2017-08-15 12:15
I will backport those fixes to 1.18 branch.

**Comment by Photon89** [comment] 2017-08-15 12:17
Cool, thanks a lot!
