### ISSUE TITLE
Document Viewer crash on pdf

### ISSUE THREAD

**Issue by Relative72** [mate-desktop/atril#137] opened 2015-05-18 05:13 UTC
Document Viewer (Atril) 1.8.1 Using poppler/cairo (0.24.5) on Mint Mate Rebecca.

While reading emagazine Woodsmith Vol 37 No 217 Viewer crashes with no indications.   Both Okular on same Linux system and Adobe Reader under Windows 7 have no problem with the emagazine.  Narrowed down problem to page 7.  Extracted it and made available at http://users.sisna.com/cebula/woodsmith_vol_37_no_217_page_7.pdf

**Comment by Relative72** [comment] 2015-06-14 03:05
Bump?

**Comment by monsta** [comment] 2015-06-14 12:29
Confirmed, still happens in 1.10.

**Comment by monsta** [comment] 2015-06-14 12:56
Turned out this is long known upstream bug in cairo (which crashed Evince as well):

https://bugs.freedesktop.org/show_bug.cgi?id=74779
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=708120
https://bugs.launchpad.net/debian/+source/cairo/+bug/1404715

**Comment by emanuele-f** [comment] 2016-09-26 14:03
I have a crash with this file: [atril_core_dump.pdf](https://github.com/mate-desktop/atril/files/493246/atril_core_dump.pdf), see [atril_core_dump.txt](https://github.com/mate-desktop/atril/files/493248/atril_core_dump.txt).

Is this issue related?

The original @Relative72 pdf link cannot be reached anymore, but I can open [one of the files](http://www.eurail.com/sites/eurail.com/files/documents/eurail_railway_map_2014.pdf) referenced as issue with no problems.

**Comment by monsta** [comment] 2016-09-30 08:36
Since the bug isn't in Atril but in a library it uses, it all depends on your distro.

**Comment by monsta** [comment] 2016-09-30 08:45
Your document also crashes Atril, but it crashes in poppler, not in cairo, and the backtrace I get is completely different. It's a separate bug so please file a separate report for it.

Also please tell us which distro/release you use, since the problem might be fixed in newer versions of poppler.

**Comment by monsta** [comment] 2016-10-09 16:48
So this is already fixed in cairo 1.14.4, therefore I'm closing it.

**Closed by monsta** 2016-10-09 16:48 UTC
Labels: confirmed
