### ISSUE TITLE
crash with eps file

### ISSUE THREAD

**Issue by samtygier** [mate-desktop/atril#98] opened 2014-11-04 11:30 UTC
I have (can can generate with gnuplot) an eps file that will crash atril 1.8.1 in fedora 20.
It is reported upstream at:
https://retrace.fedoraproject.org/faf/reports/472745/
https://bugzilla.redhat.com/show_bug.cgi?id=1159955
it looks similar to a crash in evince, so it is possibly a pixman or cairo bug really.
https://bugzilla.redhat.com/show_bug.cgi?id=1156226

    Truncated backtrace:
    Thread no. 1 (10 frames)
    #0 _mm_loadu_si128 at /usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/emmintrin.h:684
    #1 load_128_unaligned at pixman-sse2.c:370
    #2 sse2_blt at pixman-sse2.c:4764
    #3 _pixman_implementation_blt at pixman-implementation.c:250
    #4 pixman_blt at pixman.c:748
    #5 draw_image_boxes at cairo-xlib-render-compositor.c:329
    #6 upload_boxes at cairo-traps-compositor.c:1351
    #7 clip_and_composite_boxes at cairo-traps-compositor.c:1745
    #8 _cairo_traps_compositor_paint at cairo-traps-compositor.c:2057
    #9 _cairo_compositor_paint at cairo-compositor.c:65

**Comment by monsta** [comment] 2015-01-01 09:15
Hmm, I can't reproduce it with the latest atril from git master (1.9.x) in Debian Testing. Maybe the mentioned libraries are fixed here already?

**Comment by infirit** [comment] 2015-01-01 11:39
@monsta I still can, You need to go down for it to trigger.

**Comment by monsta** [comment] 2015-01-01 17:25
@infirit: no luck with that. I've tried scrolling down, changing scale, clicking everywhere. All I get is this message in the terminal:
```GPL Ghostscript 9.06: Error: Font Renderer Plugin ( FreeType ) return code = -1```

Can you post the full backtrace?

**Comment by monsta** [comment] 2016-10-09 17:45
@samtygier @raveit65: I can't make it crash with https://bugzilla.redhat.com/attachment.cgi?id=966704 or https://bugzilla.redhat.com/attachment.cgi?id=953188. Looks like these were bugs in cairo and they're fixed by now.

If you can't reproduce it, I suggest closing this report.

**Comment by raveit65** [comment] 2016-10-09 17:55
Both documents open fine here with atril-1.16.0 (gtk3) in f24.

**Closed by raveit65** 2016-10-09 17:55 UTC
Labels: unconfirmed
