### ISSUE TITLE
per-document view settings should not be saved when unmodified from user's default values

### ISSUE THREAD

**Issue by IndichRMV** [mate-desktop/atril#145] opened 2015-07-22 18:16 UTC
The per-document view settings are getting saved regardless of whether the user changed the view settings in a particular document. This results in incorrect values being saved the first time a user closes a document if the user's default view settings are different from Atril's internal default view settings.

For example, I have applied the following changes to the default view settings:
gsettings set org.mate.Atril.Default show-sidebar false;
gsettings set org.mate.Atril.Default sizing-mode 'free';

The first obviously disables the sidebar; the second makes the zoom default to 100%.

When I open a PDF file I've never opened before for the first time, both of these settings are respected. But if I close the file (without making any changes to the view settings) and open it again for the second time, the sidebar is shown and the zoom is set to "Fit Page Width" (incorrect values were saved for the per-document view settings, because Atril does not recognize the actual document view settings unless the user makes a change to them, and falls back to some internal default rather than the user's default as specified in dconf).

**Comment by victorbriz** [comment] 2015-07-24 00:04
This bug has been annoying me for years!

I prefer to view PDFs in Atril with show-toolbar:false, show-sidebar:false, dual-page:true (defaults are opposite)
Here is the simple reproducible test case that I have tried on Linux Mint 17.2 hoping it was fixed in Atril 1.10, tough luck:

1. Google for 'test pdf' and download any one
2. Open downloaded PDF in Atril and set: show-toolbar:false, show-sidebar:false, dual-page:true
3. While PDF still open click on 'Save Current Settings as Default'
4. Close PDF
5. Make copy of PDF, e.g. CTRL-C and CTRL-V
6. Open copy of PDF in Atril and enjoy: show-toolbar:false, show-sidebar:false, dual-page:true
7. Close copy of PDF
8. Open copy of PDF again and see: show-toolbar:true, show-sidebar:true, dual-page:false

To fix that I have to set: show-toolbar:false, show-sidebar:false, dual-page:true MANUALLY. FOR. EACH. AND. EVERY. PDF. I. WANT. TO. VIEW.

So the bug seems to be somewhere in SavingPerDocumentSettings() that IGNORES DEFAULT SETTINGS that USER SET and instead uses GLOBAL DEFAULT SETTINGS.

**Comment by victorbriz** [comment] 2015-07-24 01:10
[new file never opened in Atril, before Step 6] 
gvfs-info -a "metadata::*" ~/test2.pdf 
uri: file:///home/victor/test2.pdf
attributes:
  metadata::screen: 
  metadata::caja-icon-position: 

[after Step 6 but before Step 8]
gvfs-info -a "metadata::*" ~/test2.pdf 
uri: file:///home/victor/test2.pdf
attributes:
  metadata::atril::window_width: 2560
  metadata::atril::window_x: 0
  metadata::atril::window_y: 49
  metadata::atril::sidebar_size: 151
  metadata::caja-icon-position: 
  metadata::atril::window_height: 1386
  metadata::atril::page: 0
  metadata::screen: 
  metadata::atril::window_maximized: 0

[after Step 8]
gvfs-info -a "metadata::*" ~/test2.pdf 
uri: file:///home/victor/test2.pdf
attributes:
  metadata::atril::page: 0
  metadata::atril::sidebar_size: 151
  metadata::atril::window_height: 1386
  metadata::atril::window_maximized: 0
  metadata::atril::window_width: 2560
  metadata::atril::window_x: 0
  metadata::atril::window_y: 49
  metadata::caja-icon-position: 
  metadata::screen: 
  metadata::atril::sidebar_visibility: 1

**Comment by victorbriz** [comment] 2015-07-24 01:32
If after Step 6 before closing PDF I enable and disable sidebar_visibility, then 
gvfs-info -a "metadata::*" ~/test3.pdf 
uri: file:///home/victor/test3.pdf
attributes:
  metadata::atril::window_width: 2560
  metadata::atril::window_x: 0
  metadata::atril::window_y: 49
  metadata::atril::sidebar_size: 151
  metadata::caja-icon-position: 
  metadata::atril::window_height: 1386
  metadata::atril::sidebar_visibility: 0
  metadata::screen: 
  metadata::atril::page: 0
  metadata::atril::window_maximized: 0

What's interesting, there is no show_toolbar or dual-page in metadata for this file and 
$ gsettings get org.mate.Atril.Default  show-toolbar
false

Yet toolbar is showing

**Comment by victorbriz** [comment] 2015-07-24 02:33
I think issue is in shell/ev-window.c in functions: 
setup_chrome_from_metadata()
setup_sidebar_from_metadata()
setup_model_from_metadata ()
where initial values for vars:
show_toolbar
sidebar_visibility
dual_page
set to HARDCODED values instead of g_settings_get_boolean(window->priv->default_settings, "show-toolbar") - this should be initial value that you can override if metadata is present for a file, e.g.:

gboolean show_toolbar = FALSE;
if (!window->priv->metadata) {
show_toolbar = g_settings_get_boolean (window->priv->default_settings, "show-toolbar");
} else if (!ev_metadata_get_boolean (window->priv->metadata, "show_toolbar", &show_toolbar)) {
if (window->priv->is_new_doc)
show_toolbar = g_settings_get_boolean (window->priv->default_settings, "show-toolbar");
}

should be 

gboolean show_toolbar = g_settings_get_boolean (window->priv->default_settings, "show-toolbar");
if (window->priv->metadata) ev_metadata_get_boolean (window->priv->metadata, "show_toolbar", &show_toolbar);

[same for sidebar_visibility and dual_page]

**Comment by flexiondotorg** [comment] 2015-07-24 06:00
@victorbriz Please create a pull-request for us :-)

**Comment by infirit** [comment] 2015-07-24 07:32
This is I believe the fix from evince, https://github.com/GNOME/evince/commit/720eebf

Applied to Atril for testing, https://github.com/infirit/atril/commit/380b232a6fe2a8871a2fe44bd196ae32b6a4d3e5

**Comment by victorbriz** [comment] 2015-07-27 19:07
I have tried Ubuntu 15.04 and it's Evince does not remember Dual-Page settings (and it does not have option to disable Toolbar)
I have compiled Atril for myself with changed defaults :) and it works perfect! :)))
Alright, I'll work on PR for all other Atril users.

**Comment by infirit** [comment] 2015-07-27 21:50
I pushed this into master. I am hesitant to cherry-pick this for 1.10, let's have it bake in master for a while and see how things go.

**Closed by infirit** 2015-07-27 21:50 UTC
Labels: confirmed

**Comment by victorbriz** [comment] 2015-07-28 02:08
Have you confirmed this "fix from 2012" solves the issue reported and my use case? 
1. Google for 'test pdf' and download any one
2. Open downloaded PDF in Atril and set: show-toolbar:false, show-sidebar:false, dual-page:true
3. While PDF still open click on 'Save Current Settings as Default'
4. Close PDF
5. Make copy of PDF, e.g. CTRL-C and CTRL-V
6. Open copy of PDF in Atril and enjoy: show-toolbar:false, show-sidebar:false, dual-page:true
7. Close copy of PDF
8. Open copy of PDF again and see: show-toolbar:true, show-sidebar:true, dual-page:false
